package com.euph28.tson.context;

/**
 * Variable type when storing values in {@link TSONContext}
 */
public enum VariableType {

    /**
     * Variables are values generated by the user in the script
     */
    VARIABLE ("var"),

    /**
     * Properties are values generated by called keywords
     */
    PROPERTY ("prop");

    String prefix;
    VariableType(String prefix) {
        this.prefix = prefix;
    }
}
