package com.euph28.tson.context;

/**
 * Variable type when storing values in {@link TSONContext}
 */
public enum VariableType {

    /* ----- ENUMS ------------------------------ */
    /**
     * Variables are values generated by the user in the script
     */
    VARIABLE ("var"),

    /**
     * Properties are values generated by called keywords
     */
    PROPERTY ("prop");

    /* ----- VARIABLES ------------------------------ */
    final String prefix;

    /* ----- CONSTRUCTOR ------------------------------ */
    VariableType(String prefix) {
        this.prefix = prefix;
    }

    /* ----- GETTERS ------------------------------ */
    public String getPrefix() {
        return prefix;
    }
}
